model:
  name: "omniASR_LLM_1B_v2"

dataset:
  name: "omnilingual_asr_1b_levantine_custom_streaming_5minckpt_smoke_dataset"
  train_split: "train"
  valid_split: "val"
  storage_mode: "MIXTURE_PARQUET"
  task_mode: "ASR"
  mixture_parquet_storage_config:
    dataset_summary_path: "/home/MohammadNabulsi/whisper/Runs/omnilingual_asr_1b_levantine_custom_streaming_5minckpt/dataset/language_distribution_0.tsv"
    beta_corpus: 0.5
    beta_language: 0.5
  asr_task_config:
    min_audio_len: 4800
    max_audio_len: 480000
    max_num_elements: 480000
    batch_size: 1
    num_seqs_multiple_of: 1
    batch_shuffle_window: 1
    example_shuffle_window: 1
    normalize_audio: true

tokenizer:
  name: "omniASR_tokenizer_written_v2"

optimizer:
  config:
    lr: 5e-05

trainer:
  data_parallelism: "fsdp"
  fsdp:
    granularity: "stack"
    version: "v1"
    fp32_reduce: false
  freeze_encoder_for_n_steps: 0
  mixed_precision:
    dtype: "torch.bfloat16"
  grad_accumulation:
    num_batches: 1

regime:
  num_steps: 1
  validate_after_n_steps: 0
  validate_every_n_steps: 1
  checkpoint_every_n_steps: 1
  save_model_only: true
  publish_metrics_every_n_steps: 1
